#!/bin/bash
# =============================================================================
# Configuration Management
# =============================================================================

CONFIG_DIR="${HOME}/.config/remote-macOS-agents"
CONFIG_FILE="${CONFIG_DIR}/config"
JOB_DIR="${CONFIG_DIR}/jobs"

# Default configuration
DEFAULT_ROLE="unknown"
DEFAULT_SERVER_HOSTNAME="macmini"
DEFAULT_SERVER_USER="$(whoami)"
DEFAULT_PANEL_PORT="8080"
DEFAULT_TAILSCALE_HOSTNAME="macmini"

# Load configuration
load_config() {
	if [[ -f "$CONFIG_FILE" ]]; then
		source "$CONFIG_FILE"
	else
		ROLE="$DEFAULT_ROLE"
		SERVER_HOSTNAME="$DEFAULT_SERVER_HOSTNAME"
		SERVER_USER="$DEFAULT_SERVER_USER"
		PANEL_PORT="$DEFAULT_PANEL_PORT"
		TAILSCALE_HOSTNAME="$DEFAULT_TAILSCALE_HOSTNAME"
	fi
}

# Save configuration
save_config() {
	mkdir -p "$CONFIG_DIR"

	cat >"$CONFIG_FILE" <<EOF
# Remote macOS Agents Configuration
# Generated by setup.sh

ROLE="$ROLE"
SERVER_HOSTNAME="$SERVER_HOSTNAME"
SERVER_USER="$SERVER_USER"
PANEL_PORT="$PANEL_PORT"
TAILSCALE_HOSTNAME="$TAILSCALE_HOSTNAME"

EOF

	log_success "Configuration saved to ${CONFIG_FILE}"
}

# Update a specific config value
update_config() {
	local key="$1"
	local value="$2"

	mkdir -p "$CONFIG_DIR"

	if [[ ! -f "$CONFIG_FILE" ]]; then
		touch "$CONFIG_FILE"
	fi

	if grep -q "^${key}=" "$CONFIG_FILE" 2>/dev/null; then
		sed -i '' "s|^${key}=.*|${key}=\"${value}\"|" "$CONFIG_FILE"
	else
		echo "${key}=\"${value}\"" >>"$CONFIG_FILE"
	fi
}

# Get Tailscale hostname
get_magicdns_hostname() {
	echo "${TAILSCALE_HOSTNAME}.tailnet.ts.net"
}

# Show current configuration
show_config() {
	log_header "Current Configuration"

	echo -e "  Role:           ${BOLD}${ROLE}${NC}"
	echo -e "  Server Host:    ${BOLD}${SERVER_HOSTNAME}${NC}"
	echo -e "  Server User:    ${BOLD}${SERVER_USER}${NC}"
	echo -e "  Panel Port:     ${BOLD}${PANEL_PORT}${NC}"
	echo -e "  Tailscale DNS:  ${BOLD}$(get_magicdns_hostname)${NC}"
}
